### ISSUE TITLE
unable to install ex_faiss

### ISSUE THREAD

**Issue by singhdavinderpa1** [elixir-nx/ex_faiss#11]
I am getting following error when I try to compile ex_faiss with mix deps.compile ex_faiss

![image](https://github.com/elixir-nx/ex_faiss/assets/20025741/90dade9d-1536-4ee5-90cf-73412c1cb313)

**Comment by josevalim** [comment]
We are no longer planning to move ahead with this library. Please check the README.

> Note: this library is experimental and not a priority. Consider using [HNSWLib](https://github.com/elixir-nx/hnswlib) instead.

If you must use it, then feel free to explore it, but we won't be helping much. Good luck!
